version: "3.8"

services: 
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
    #environment: 
    #- MONGO_INITDB_ROOT_USERNAME=farrukh
    #MONGO_INITDB_ROOT_USERNAME: farrukh
    #MONGO_INITDB_ROOT_PASSWORD: adminfarrukh
    env_file: 
    - ./env/mongo.env


  backend:
    build: ./backend
    #More Specific and long method
    #build:
    #context: ./backend
    #dockerfile: Dockerfile      #if your filename is other than Dockerfile you can put here   
    #args:
      #someargs: 1
    ports: 
      - 80:80
    volumes: 
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file: 
    - ./env/backend.env
    depends_on: 
      - mongodb


  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
    volumes: 
      - ./frontend/src:/app/src

    stdin_open: true
    tty: true
    depends_on: 
      - backend


volumes: 
  data:
  logs: